const REFRESH_PROXIES_LIST_EVERY_X_HOUR = 12;

const USE_DEFAULT_IP_AFTER_X_FAILED_PROXIES = 20;



module.exports = {
    REFRESH_PROXIES_LIST_EVERY_X_HOUR,
    USE_DEFAULT_IP_AFTER_X_FAILED_PROXIES
};